config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cases, only: [ :index, :show ] do
    resources :questions, only: [ :index ]
  end
  resources :questions, only: :show do
    resources :answers, only: [ :new, :create ]
  end
  resources :answers, only: [ :index, :show ]
  resources :orders, only: [:show, :create]
  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end
  get 'dashboard', to: 'profiles#dashboard'
  get 'skills', to: 'profiles#skills'
  get 'industries', to: 'profiles#industries'
  get 'follow/:id', to: 'companies#follow', as: :follow
  get 'unfollow/:id', to: 'companies#unfollow', as: :unfollow
  get 'voting/:id', to: 'answers#voting', as: :voting
  get 'knowledge', to: 'profiles#knowledge'
  get 'myclients', to: 'profiles#myclients'
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :case
  has_many :answers
  validates :skills, inclusion: { in: ["Logic and rigorous thinking", "Business sense & culture", "Mathematics skills"]}
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @cas = Case.find(params[:case_id])
    @attempt = current_user.attempts.last
    @attempt.update(completed: true)
    @questions = policy_scope(Question)
    @questionstothiscase = Question.where(case_id: @cas.id)
  end

  def show
    @question = Question.find(params[:id])
    if params[:attempt] == "new"
      @attempt = Attempt.create(user_id: current_user.id, case_id: @question.case.id)
    end
    @answer = Answer.new
    authorize @question
  end
end

app/views/questions/index.html.erb
<div class="trianglify-twisted">
  <div class="first-box">
    <div class="row">
      <div class="col col-md-11 title-question">
        <h1> <%= @questionstothiscase.first.case.name.upcase %> <%= @questionstothiscase.first.case.difficulty.html_safe  %> - <em> Your score </em></h1>
      </div>

      <div class="col col-md-1">
        <%= link_to '<i class="fas fa-chevron-circle-right"></i>'.html_safe, cases_path, class: "back text-right"  %>
      </div>
    </div>

     <div class="row">
      <div class="col col-md-12">

           <div class="score-bar blue stripes score-card-questions">
            <span style="width: <%= @questionstothiscase.first.case.attempts.last.score.to_i.fdiv(@questionstothiscase.length.to_i * 3) * 100 %>%"></span>
           </div>
              <p class="text-right">  Your score to this test: <%= @questionstothiscase.first.case.attempts.last.score %> / <%= @questionstothiscase.length.to_i * 3  %> </p>
        </div>
      </div>

    <div class="row">
      <div class="col col-md-12">
        <div class="container-index-blue">
          <H6> <strong> <em> <%=  @questionstothiscase.first.case.content.html_safe %> </em></strong></h6>
        </div>
      </div>
    </div>



    <% @questionstothiscase.reverse.each do  |question| %>
      <div class="row">
        <div class="col col-md-1">
          <div class="question-number">
            <h1> <%= question.position %></h1>
          </div>
        </div>
        <div class="col col-md-11">
          <div class="container-index-blue">
            <h6>
             <strong><%= question.content.gsub(/\n/,'<br>').html_safe %></strong>
            </h6>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col col-md-11 offset-md-1">
          <div class="container-question-index">
            <% if question.answer_ids.last.nil? %>
            <% elsif %>
              <h6>My answer:</h6>
              <p class="question-answer"> <%= Answer.find(question.answer_ids.last).content.html_safe %></p>
            <% end %>
              <h6>Correction: </h6>
              <p class="question-correction"> <%= question.correction.gsub(/\n/,'<br>').html_safe %></p>
          </div>
        </div>
      </div>
    <% end %>


  </div>
</div>

<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Get to the best consulting firms <i class="fas fa-heart"></i>
  </div>
</div>

app/views/questions/show.html.erb
<div class="trianglify-twisted">
  <div class="first-box">
    <div class="row">
      <div class="col col-md-10">
        <h2 class="title-question"> <%= @question.case.name.upcase %> <%= @question.case.difficulty.html_safe  %> </h2>
      </div>
      <div class="col col-md-2">
        <div class="time-indication">
          <div class="timing-by-case">
            <i class="far fa-clock"></i>
            <p> <%= @question.timing %> mins </p>

          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col col-md-12">

        <div class="progress md-progress" style="height: 20px">
          <div class="progress-bar progress-bar-bis" role="progressbar" style="width: <%= @question.position.to_i.fdiv(@question.case.questions.last.position.to_i) * 100 %>%" aria-valuenow="<%= @question.position.to_i.fdiv(@question.case.questions.last.position.to_i) * 100%>" aria-valuemin="0" aria-valuemax="100">
          </div>

      </div>

      <p class="text-right"> <em> <%= @question.case.questions.last.position.to_i %> questions</em></p>

      </div>
    </div>
    <div>

    </div>
    <div class="row">

      <div class="col col-md-12">
        <div class="container-question-blue">
          <div class="question-text">
            <h5> <%=  @question.content.gsub(/\n/,'<br>').html_safe %></h5>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col col-md-12">
          <% if @question.photo.nil? %>
          <% else %>
            <div class="container-question container-picture" style="background-image: url(<%=cl_image_path(@question.photo)%>)">
            </div>
          <% end %>
        </div>
      </div>

    <div class="row">
      <div class="col col-md-8">
        <div class="container-question">
          <%= simple_form_for [@question, @answer] do |f| %>
            <%= f.input :content, input_html: { type: "textarea", class: "your-turn" }, placeholder: "Ace here!", label: "Your answer: "%>
        </div>
      </div>
      <div class="col col-md-4">
          <div id="countdown">
            <svg class="mysvg">
              <circle style="animation-duration: <%= @question.timing * 60 %>s" r="46" cx="50" cy="50"></circle>
                <div id="startValuesAndTargetExample">
                    <div id="exact-timing" class="values"></div>
                </div>
            </svg>
          </div>
            <div class="next-question">
              <h3>NEXT</h3>
              <%= f.submit "", :class => "btn btn-next", :id => "btn-send-timer" do %>
                <div class="position-button-next">
                    <i class="fas fa-chevron-circle-right"></i>
                  <% end %>
                </div>
              <% end %>
            </div>
      </div>
    </div>
  </div>
</div>









        <p id="questiontiming" data-timer="<%= @question.timing %>", data-url="<%= cases_url %>"> <em><strong> <% @question.timing  %> </strong> </em> </p>

<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Get to the best consulting firms <i class="fas fa-heart"></i>
  </div>
</div>