config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cases, only: [ :index, :show ] do
    resources :questions, only: [ :index ]
  end
  resources :questions, only: :show do
    resources :answers, only: [ :new, :create ]
  end
  resources :answers, only: [ :index, :show ]
  resources :orders, only: [:show, :create]
  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end
  get 'dashboard', to: 'profiles#dashboard'
  get 'skills', to: 'profiles#skills'
  get 'industries', to: 'profiles#industries'
  get 'follow/:id', to: 'companies#follow', as: :follow
  get 'unfollow/:id', to: 'companies#unfollow', as: :unfollow
  get 'voting/:id', to: 'answers#voting', as: :voting
  get 'knowledge', to: 'profiles#knowledge'
  get 'myclients', to: 'profiles#myclients'
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def dashboard
    @user = current_user
    @companies = Company.all
    @cases = Case.all
    @last_attempt = Attempt.where(user_id: current_user).last
    @last_attempt_completed = Attempt.all.where(completed: true, user_id: current_user).last
    authorize @user
  end

  def skills
    @user = current_user
    @companies = Company.all
    @cases = Case.all
    @questions_business = Question.where(skills: "Business sense & culture")
    @questions_logic = Question.where(skills: "Logic and rigorous thinking")
    @questions_math = Question.where(skills: "Mathematics skills")
    @last_attempt_completed = Attempt.all.where(completed: true, user_id: current_user).last
    authorize @user
  end

  def industries
    @user = current_user
    @companies = Company.all
    @cases = Case.all
    @last_attempt_completed = Attempt.all.where(completed: true, user_id: current_user).last
    authorize @user
  end

  def knowledge
    @user = current_user
    @companies = Company.all
    @users = User.all
    authorize @user
  end
end

app/views/profiles/dashboard.html.erb
<div class="container-profile">
  <div class="profile">
    <% if @user.photo.url.nil? %>
      <%=  image_tag "avatar.png", width: 200, height: 200, class: "avatar-profile align-avatar", style: "background: grey" %>
    <% else %>
      <%= cl_image_tag @user.photo, width: 200, height: 200, crop: :thumb, gravity: :face, class: "avatar-profile align-avatar" %>
    <% end %>
  </div>

  <div class="profile-data">
    <h2>  <%=  @user.first_name %> <%=  @user.last_name.upcase %></h2>
    <p> <em> <%= @user.email %> </em></p>
    <%= link_to "Practice", cases_path, class: "btn btn-flat" %>
  </div>


</div>


<div class="score-comment">
  <h4>Progression</h4>
</div>
<div class="container-score-comment">
  <div>
    <% if @last_attempt_completed.nil? %>
      <h4 class="dashboard-title"> No case done. Start acing the case!</h4>

    <% else %>
      <% number_last_casedone = @last_attempt_completed.case.position %>
      <% number_questions = 0 %>
      <% for i in 1..number_last_casedone  %>
        <% current_case = Case.where(position: i) %>
        <% number_questions += Question.where(case_id: current_case.ids[0]).length.to_i %>
      <% end %>
      <% if current_user.score.to_i.fdiv(number_questions * 3) < 0.33 %>
        <h4 class="dashboard-title"> Out of  <%= number_questions * 3 %> points possible so far, you obtained <%= current_user.score %> / <%= number_questions * 3 %> </h4>
        <p class="dashboard-subtitle"> Keep practicing, practice makes perfect! </p>
      <% elsif current_user.score.to_i.fdiv(number_questions * 3) > 0.66 %>
        <h4 class="dashboard-title"> Your current score is <%= current_user.score %> / <%= number_questions * 3 %>. Excellent, keep up the good work!  </h4>
        <p class="dashboard-subtitle"> Keep practicing, practice makes perfect! </p>
      <% else %>
        <h4 class="dashboard-title"> Your current score is <%= current_user.score %> / <%= number_questions * 3 %>. Not bad, more practice is needed!  </h4>
        <p class="dashboard-subtitle"> Keep practicing, practice makes perfect! </p>
      <% end %>
    <% end %>

  </div>
  <div class="container-tabs">
    <ul class="list-inline tabs-underlined mytabs">
      <li>
        <%= link_to "Global", "#", class: "tab-underlined active" %>
      </li>
      <li>
        <%= link_to "By skills", skills_path, class: "tab-underlined" %>
      </li>
      <li>
        <%= link_to "By industry", industries_path, class: "tab-underlined" %>
      </li>
    </ul>
  </div>
</div>
<!-- <h4 class="dashboard-title">Progression</h4> -->


<div class="container-dashboard">

  <div class="dashboard">
    <p class="skill-name">Score</p>
    <div class="dashboard-description">
      <div class="dashboard-description-content">
        <h2> <%= current_user.score.to_i %> points </h2>
        <p> Out of <%= Question.all.length * 3 %> points </p>
      </div>
      <%=  image_tag "audio.svg", height: 50%>
    </div>
    <div class="score-bar blue stripes">
      <span style="width: <%= current_user.score.to_i.fdiv(Question.all.length * 3) * 100 %>%"></span>
    </div>
  </div>

  <div class="dashboard">
    <p class="skill-name">Cases done</p>
     <div class="dashboard-description">
      <div class="dashboard-description-content">
      <% if  @last_attempt_completed.nil?%>
        <h2> No case done </h2>
      <% else %>
        <h2> <%= @last_attempt_completed.case.position %> cases done </h2>
      <% end %>
      <p> Out of <%= Case.all.length %> cases </p>
      </div>
      <%=  image_tag "screen.svg", height: 50%>
    </div>
    <section>
      <ol class="progress-bar">
        <% @cases.each do |c| %>

          <% if c.attempts.where(user_id: current_user.id).last.nil? %>
            <li><span> <%= c.name %> </span></li>

          <% elsif c.attempts.where(user_id: current_user.id).last.completed == true && @last_attempt.case.position == c.position %>
            <li class="is-active"><span> <%= c.name %> </span></li>

          <% elsif c.attempts.last.completed == true %>
            <li class="is-complete"><span> <%= c.name %> </span></li>

          <% else %>
            <li><span> <%= c.name %> </span></li>

          <% end %>
        <% end %>
      </ol>
    </section>
  </div>


</div>

<!-- div class="score-comment">
  <h4>Progression</h4>
</div>
 -->
<!-- div class="container-dashboard">

  <div class="row companies-container">
    <% @companies.each do |company| %>
      <div class= "col-sm-3 col col-xs-12 text-center">
        <% if company.followed_by?(@user) %>
            <%= link_to unfollow_path(company) do %>
              <div class="company-card company-active" style="background-image: url(<%=cl_image_path(company.logo) %>)">
              <%#= cl_image_tag company.logo, width: 100, height: 100, crop: :fill %>
              </div>
            <% end %>

        <% else %>
          <%= link_to follow_path(company) do %>
            <div class="company-card" style="background-image: url(<%=cl_image_path(company.logo) %>)">
              <%#= cl_image_tag company.logo, width: 100, height: 100, crop: :fill  %>
            </div>
          <% end %>

        <% end %>
      </div>
    <% end %>
  </div>
</div> -->


</div>
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Get to the best consulting firms <i class="fas fa-heart"></i>
  </div>
</div>

app/views/profiles/industries.html.erb
<div class="container-profile">
  <div class="profile">
    <% if @user.photo.url.nil? %>
      <%=  image_tag "avatar.png", width: 200, height: 200, class: "avatar-profile align-avatar", style: "background: grey" %>
    <% else %>
      <%= cl_image_tag @user.photo, width: 200, height: 200, crop: :thumb, gravity: :face, class: "avatar-profile align-avatar" %>
    <% end %>
  </div>

  <div class="profile-data">
    <h2>  <%=  @user.first_name %> <%=  @user.last_name.upcase %></h2>
    <p> <em> <%= @user.email %> </em></p>
    <%= link_to "Practice", cases_path, class: "btn btn-flat" %>
  </div>

  <!-- <div class="row companies-container set-your-obj">
    <h5> Set your objectives </h5>
  </div>

  <div class="row companies-container">
    <% @companies.each do |company| %>
      <div class= "col-sm-3 col col-xs-12 text-center">
        <% if company.followed_by?(@user) %>
            <%= link_to unfollow_path(company) do %>
              <div class="company-card company-active" style="background-image: url(<%=cl_image_path(company.logo) %>)">
              <%#= cl_image_tag company.logo, width: 100, height: 100, crop: :fill %>
              </div>
            <% end %>

        <% else %>
          <%= link_to follow_path(company) do %>
            <div class="company-card" style="background-image: url(<%=cl_image_path(company.logo) %>)">
              <%#= cl_image_tag company.logo, width: 100, height: 100, crop: :fill  %>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div> -->

</div>


<div class="score-comment">
  <h4>Progression</h4>
</div>
<div class="container-score-comment">
  <div>
    <% if @last_attempt_completed.nil? %>
      <h4 class="dashboard-title"> No case done. Start acing the case!</h4>

    <% else %>
      <% number_last_casedone = @last_attempt_completed.case.position %>
      <% number_questions = 0 %>
      <% for i in 1..number_last_casedone  %>
        <% current_case = Case.where(position: i) %>
        <% number_questions += Question.where(case_id: current_case.ids[0]).length.to_i %>
      <% end %>
      <% if current_user.score.to_i.fdiv(number_questions * 3) < 0.33 %>
        <h4 class="dashboard-title"> Out of  <%= number_questions * 3 %> points possible so far, you obtained <%= current_user.score %> / <%= number_questions * 3 %> </h4>
        <p class="dashboard-subtitle"> Keep practicing, practice makes perfect! </p>
      <% elsif current_user.score.to_i.fdiv(number_questions * 3) > 0.66 %>
        <h4 class="dashboard-title"> Your current score is <%= current_user.score %> / <%= number_questions * 3 %>. Excellent, keep up the good work!  </h4>
        <p class="dashboard-subtitle"> Keep practicing, practice makes perfect! </p>
      <% else %>
        <h4 class="dashboard-title"> Your current score is <%= current_user.score %> / <%= number_questions * 3 %>. Not bad, more practice is needed!  </h4>
        <p class="dashboard-subtitle"> Keep practicing, practice makes perfect! </p>
      <% end %>
    <% end %>

  </div>
  <div class="container-tabs">
    <ul class="list-inline tabs-underlined mytabs">
      <li>
        <%= link_to "Global", dashboard_path, class: "tab-underlined" %>
      </li>
      <li>
        <%= link_to "By skills", skills_path, class: "tab-underlined" %>
      </li>
      <li>
        <%= link_to "By industry", "#", class: "tab-underlined active" %>
      </li>
    </ul>
  </div>
</div>



<div class="container-industries">
  <div class="dashboard-industries">
    <p class="skill-name">Consumer goods</p>
    <div class="dashboard-description">
      <div class="dashboard-description-content">
        <h2> <%= current_user.consumer_goods.to_i %> points </h2>
        <% sum = 0 %>
        <% Case.where(industry: "Consumer goods").each { |c| sum += c.questions.length }  %>
        <p> Out of <%= sum * 3 %> points </p>
      </div>
      <%=  image_tag "audio.svg", height: 50%>
    </div>
    <div class="score-bar blue stripes">
      <span style="width: <%= current_user.consumer_goods.to_i.fdiv( sum * 3) * 100 %>%"></span>
    </div>
  </div>

  <div class="dashboard-industries">
    <p class="skill-name">Oil & gas</p>
    <div class="dashboard-description">
      <div class="dashboard-description-content">
        <h2> <%= current_user.oil_and_gas.to_i %> points </h2>
         <% sum = 0 %>
        <% Case.where(industry: "Oil & gas").each { |c| sum += c.questions.length }  %>
        <p> Out of <%= sum * 3 %> points </p>
      </div>
      <%=  image_tag "screen.svg", height: 50%>
    </div>
    <div class="score-bar blue stripes">
      <span style="width: <%= current_user.oil_and_gas.to_i.fdiv(sum * 3) * 100 %>%"></span>
    </div>
  </div>

  <div class="dashboard-industries">
    <p class="skill-name">Manufacturing</p>
    <div class="dashboard-description">
      <div class="dashboard-description-content">
        <h2> <%= current_user.manufacturing.to_i %> points </h2>
         <% sum = 0 %>
        <% Case.where(industry: "Manufacturing").each { |c| sum += c.questions.length }  %>
        <p> Out of <%= sum * 3 %> points </p>
      </div>
      <%=  image_tag "sofa.svg", height: 50%>
    </div>
    <div class="score-bar blue stripes">
      <span style="width: <%= current_user.manufacturing.to_i.fdiv(sum * 3) * 100 %>%"></span>
    </div>
  </div>

</div>

<div class="container-industries">
  <div class="dashboard-industries">
    <p class="skill-name">Financial services</p>
    <div class="dashboard-description">
      <div class="dashboard-description-content">
        <h2> <%= current_user.financial_services.to_i %> points </h2>
         <% sum = 0 %>
        <% Case.where(industry: "Financial services").each { |c| sum += c.questions.length }  %>
        <p> Out of <%= sum * 3 %> points </p>
      </div>
      <%=  image_tag "tablet.svg", height: 50%>
    </div>
    <div class="score-bar blue stripes">
      <span style="width: <%= current_user.financial_services.to_i.fdiv(sum * 3) * 100 %>%"></span>
    </div>
  </div>

  <div class="dashboard-industries">
    <p class="skill-name">Private Equity</p>
    <div class="dashboard-description">
      <div class="dashboard-description-content">
        <h2> <%= current_user.private_equity.to_i %> points </h2>
         <% sum = 0 %>
        <% Case.where(industry: "Private Equity").each { |c| sum += c.questions.length }  %>
        <p> Out of <%= sum * 3 %> points </p>
      </div>
      <%=  image_tag "computer.svg", height: 50%>
    </div>
    <div class="score-bar blue stripes">
      <span style="width: <%= current_user.private_equity.to_i.fdiv(sum * 3) * 100 %>%"></span>
    </div>
  </div>

  <div class="dashboard-industries">
    <p class="skill-name">Pharmaceuticals</p>
    <div class="dashboard-description">
      <div class="dashboard-description-content">
        <h2> <%= current_user.pharmaceuticals.to_i %> points </h2>
         <% sum = 0 %>
        <% Case.where(industry: "Pharmaceuticals").each { |c| sum += c.questions.length }  %>
        <p> Out of <%= sum * 3 %> points </p>
      </div>
      <%=  image_tag "megaphone.svg", height: 50%>
    </div>
    <div class="score-bar blue stripes">
      <span style="width: <%= current_user.pharmaceuticals.to_i.fdiv(sum * 3) * 100 %>%"></span>
    </div>
  </div>

</div>

<div class="container-industries">
  <div class="dashboard-industries">
    <p class="skill-name">Airline</p>
    <div class="dashboard-description">
      <div class="dashboard-description-content">
        <h2> <%= current_user.airline.to_i %> points </h2>
         <% sum = 0 %>
        <% Case.where(industry: "Airline").each { |c| sum += c.questions.length }  %>
        <p> Out of <%= sum * 3 %> points </p>
      </div>
      <%=  image_tag "audio.svg", height: 50%>
    </div>
    <div class="score-bar blue stripes">
      <span style="width: <%= current_user.airline.to_i.fdiv(sum * 3) * 100 %>%"></span>
    </div>
  </div>

  <div class="dashboard-industries">
    <p class="skill-name">TM & T</p>
    <div class="dashboard-description">
      <div class="dashboard-description-content">
        <h2> <%= current_user.tmt.to_i %> points </h2>
         <% sum = 0 %>
        <% Case.where(industry: "Technology, Media & Telecommunication").each { |c| sum += c.questions.length }  %>
        <p> Out of <%= sum * 3 %> points </p>
      </div>
      <%=  image_tag "screen.svg", height: 50%>
    </div>
    <div class="score-bar blue stripes">
      <span style="width: <%= current_user.tmt.to_i.fdiv(sum * 3) * 100 %>%"></span>
    </div>
  </div>

  <div class="dashboard-industries">
    <p class="skill-name">Public sector</p>
    <div class="dashboard-description">
      <div class="dashboard-description-content">
        <h2> <%= current_user.public_sector.to_i %> points </h2>
         <% sum = 0 %>
        <% Case.where(industry: "Public sector").each { |c| sum += c.questions.length }  %>
        <p> Out of <%= sum * 3 %> points </p>
      </div>
      <%=  image_tag "computer.svg", height: 50%>
    </div>
    <div class="score-bar blue stripes">
      <span style="width: <%= current_user.public_sector.to_i.fdiv(sum * 3) * 100 %>%"></span>
    </div>
  </div>

</div>

<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Get to the best consulting firms <i class="fas fa-heart"></i>
  </div>
</div>

app/views/profiles/skills.html.erb
<div class="container-profile">
  <div class="profile">
    <% if @user.photo.url.nil? %>
      <%=  image_tag "avatar.png", width: 200, height: 200, class: "avatar-profile align-avatar", style: "background: grey" %>
    <% else %>
      <%= cl_image_tag @user.photo, width: 200, height: 200, crop: :thumb, gravity: :face, class: "avatar-profile align-avatar" %>
    <% end %>
  </div>


  <div class="profile-data">
    <h2>  <%=  @user.first_name %> <%=  @user.last_name.upcase %></h2>
    <p> <em> <%= @user.email %> </em></p>
    <%= link_to "Practice", cases_path, class: "btn btn-flat" %>
  </div>

  <!-- <div class="row companies-container set-your-obj">
    <h5> Set your objectives </h5>
  </div>

  <div class="row companies-container">
    <% @companies.each do |company| %>
      <div class= "col-sm-3 col col-xs-12 text-center">
        <% if company.followed_by?(@user) %>
            <%= link_to unfollow_path(company) do %>
              <div class="company-card company-active" style="background-image: url(<%=cl_image_path(company.logo) %>)">
              <%#= cl_image_tag company.logo, width: 100, height: 100, crop: :fill %>
              </div>
            <% end %>

        <% else %>
          <%= link_to follow_path(company) do %>
            <div class="company-card" style="background-image: url(<%=cl_image_path(company.logo) %>)">
              <%#= cl_image_tag company.logo, width: 100, height: 100, crop: :fill  %>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div> -->

</div>

<div class="score-comment">
  <h4>Progression</h4>
</div>
<div class="container-score-comment">
  <div>
    <% if @last_attempt_completed.nil? %>
      <h4 class="dashboard-title"> No case done. Start acing the case!</h4>

    <% else %>
      <% number_last_casedone = @last_attempt_completed.case.position %>
      <% number_questions = 0 %>
      <% for i in 1..number_last_casedone  %>
        <% current_case = Case.where(position: i) %>
        <% number_questions += Question.where(case_id: current_case.ids[0]).length.to_i %>
      <% end %>
      <% if current_user.score.to_i.fdiv(number_questions * 3) < 0.33 %>
        <h4 class="dashboard-title"> Out of  <%= number_questions * 3 %> points possible so far, you obtained <%= current_user.score %> / <%= number_questions * 3 %> </h4>
        <p class="dashboard-subtitle"> Keep practicing, practice makes perfect! </p>
      <% elsif current_user.score.to_i.fdiv(number_questions * 3) > 0.66 %>
        <h4 class="dashboard-title"> Your current score is <%= current_user.score %> / <%= number_questions * 3 %>. Excellent, keep up the good work!  </h4>
        <p class="dashboard-subtitle"> Keep practicing, practice makes perfect! </p>
      <% else %>
        <h4 class="dashboard-title"> Your current score is <%= current_user.score %> / <%= number_questions * 3 %>. Not bad, more practice is needed!  </h4>
        <p class="dashboard-subtitle"> Keep practicing, practice makes perfect! </p>
      <% end %>
    <% end %>
  </div>
  <div class="container-tabs">
     <ul class="list-inline tabs-underlined mytabs">
      <li>
        <%= link_to "Global", dashboard_path, class: "tab-underlined" %>
      </li>
      <li>
        <%= link_to "By skills", skills_path, class: "tab-underlined active" %>
      </li>
      <li>
        <%= link_to "By industry", industries_path, class: "tab-underlined" %>
      </li>
    </ul>
  </div>
</div>




<div class="container-dashboard">

  <div class="dashboard-skills">
    <p class="skill-name">Logic and rigorous thinking</p>
    <div class="dashboard-description">
      <div class="dashboard-description-content">
        <h2> <%= current_user.logic.to_i %> points </h2>
        <p> Out of <%= @questions_logic.length * 3 %> points </p>
      </div>
      <%=  image_tag "screen.svg", height: 50%>
    </div>
    <div class="score-bar blue stripes">
      <span style="width: <%= current_user.logic.to_i.fdiv(@questions_logic.length * 3) * 100 %>%"></span>
    </div>
  </div>

    <div class="dashboard-skills">
      <p class="skill-name">Business sense & culture</p>
    <div class="dashboard-description">
      <div class="dashboard-description-content">
        <h2> <%= current_user.business_sense.to_i %> points </h2>
        <p> Out of <%= @questions_business.length * 3%> points </p>
      </div>
      <%=  image_tag "sofa.svg", height: 50%>
    </div>
    <div class="score-bar blue stripes">
      <span style="width: <%= current_user.business_sense.to_i.fdiv(@questions_business.length * 3) * 100 %>%"></span>
    </div>
  </div>

    <div class="dashboard-skills">
      <p class="skill-name">Mathematics skills</p>
    <div class="dashboard-description">
      <div class="dashboard-description-content">
        <h2> <%= current_user.mathematics.to_i %> points </h2>
        <p> Out of <%= @questions_math.length * 3 %> points </p>
      </div>
      <%=  image_tag "audio.svg", height: 50%>
    </div>
    <div class="score-bar blue stripes">
      <span style="width: <%= current_user.mathematics.to_i.fdiv(@questions_math.length * 3) * 100 %>%"></span>
    </div>
  </div>





</div>

</div>
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Get to the best consulting firms <i class="fas fa-heart"></i>
  </div>
</div>