config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cases, only: [ :index, :show ] do
    resources :questions, only: [ :index ]
  end
  resources :questions, only: :show do
    resources :answers, only: [ :new, :create ]
  end
  resources :answers, only: [ :index, :show ]
  resources :orders, only: [:show, :create]
  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end
  get 'dashboard', to: 'profiles#dashboard'
  get 'skills', to: 'profiles#skills'
  get 'industries', to: 'profiles#industries'
  get 'follow/:id', to: 'companies#follow', as: :follow
  get 'unfollow/:id', to: 'companies#unfollow', as: :unfollow
  get 'voting/:id', to: 'answers#voting', as: :voting
  get 'knowledge', to: 'profiles#knowledge'
  get 'myclients', to: 'profiles#myclients'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar fixed-top navbar-expand-sm navbar-light navbar-lewagon <%= @myclass if defined? @myclass %> ">
  <%= link_to "Casebreaker", root_path, class: "navbar-brand nav-linkk" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Practice", cases_path, class: "nav-linkk pushdown-second" %>
        </li>
        <li class="nav-item">
          <%= link_to "Dashboard", dashboard_path, class: "nav-linkk pushdown-first" %>
        </li>
        <li class="nav-item">
          <%= link_to "Resources", knowledge_path, class: "nav-linkk pushdown-third" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.url.nil? %>
            <%=  image_tag "avatar.png", width: 150, height: 150, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" } %>
          <% else %>
            <%= cl_image_tag current_user.photo, width: 150, height: 150, crop: :thumb, gravity: :face, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" } %>
          <% end %>

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Edit profile", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_session_path, class: "nav-linkk" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>