config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cases, only: [ :index, :show ] do
    resources :questions, only: [ :index ]
  end
  resources :questions, only: :show do
    resources :answers, only: [ :new, :create ]
  end
  resources :answers, only: [ :index, :show ]
  resources :orders, only: [:show, :create]
  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end
  get 'dashboard', to: 'profiles#dashboard'
  get 'skills', to: 'profiles#skills'
  get 'industries', to: 'profiles#industries'
  get 'follow/:id', to: 'companies#follow', as: :follow
  get 'unfollow/:id', to: 'companies#unfollow', as: :unfollow
  get 'voting/:id', to: 'answers#voting', as: :voting
  get 'knowledge', to: 'profiles#knowledge'
  get 'myclients', to: 'profiles#myclients'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :attempt
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index
    @answers = policy_scope(Answer)
    @users = User.all
  end

  def new
    @question = Question.find(params[:question_id])
    @answer = Answer.new
    authorize @answer
  end

  def create
    @question = Question.find(params[:question_id])
    @attempt = Attempt.where(user_id: current_user.id, case_id: @question.case.id).last
    @answer = Answer.new(answer_params)
    @answer.question_id = @question.id
    @answer.attempt_id = @attempt.id
    if @answer.save
      redirect_to answer_path(@answer)
    else
      render :new
    end
    authorize @answer
  end

  def show
    @answer = Answer.find(params[:id])
    @question = @answer.question
    correct = 0
    @question.keywords.each do |keyword|
      if @answer.content.include?(keyword)
        correct += 1
      end
    end
    @user = current_user
    @attempt = Attempt.where(user_id: current_user.id, case_id: @question.case.id).last
    if correct == 0
      @answer.correctness = "Keep working. Practice makes perfect 🤔"
    elsif correct == @question.keywords.length
      @answer.correctness = "Perfect. You are on the way for MBB 🎉"
      @user.score += 3
      @attempt.score += 3

      if @question.skills == "Logic and rigorous thinking"
        @user.logic += 3
      elsif @question.skills == "Business sense & culture"
        @user.business_sense += 3
      elsif @question.skills == "Mathematics skills"
        @user.mathematics += 3
      end

      if @question.case.industry == "Consumer goods"
        @user.consumer_goods += 3
      elsif @question.case.industry == "Oil & gas"
        @user.oil_and_gas += 3
      elsif @question.case.industry == "Manufacturing"
        @user.manufacturing += 3
      elsif @question.case.industry == "Financial services"
        @user.financial_services += 3
      elsif @question.case.industry == "Private Equity"
        @user.private_equity += 3
      elsif @question.case.industry == "Pharmaceuticals"
        @user.pharmaceuticals += 3
      elsif @question.case.industry == "Airline"
        @user.airline += 3
      elsif @question.case.industry == "Technology, Media & Telecommunication"
        @user.tmt += 3
      elsif @question.case.industry == "Non-profit"
        @user.non_profit += 3
      elsif @question.case.industry == "Public sector"
        @user.public_sector += 3
      end

    elsif correct < @question.keywords.length.fdiv(2)
      @answer.correctness = "Not bad. You can still improve your skills 😓"
      @user.score += 1
      @attempt.score += 1

      if @question.skills == "Logic and rigorous thinking"
        @user.logic += 1
      elsif @question.skills == "Business sense & culture"
        @user.business_sense += 1
      elsif @question.skills == "Mathematics skills"
        @user.mathematics += 1
      end

      if @question.case.industry == "Consumer goods"
        @user.consumer_goods += 1
      elsif @question.case.industry == "Oil & gas"
        @user.oil_and_gas += 1
      elsif @question.case.industry == "Manufacturing"
        @user.manufacturing += 1
      elsif @question.case.industry == "Financial services"
        @user.financial_services += 1
      elsif @question.case.industry == "Private Equity"
        @user.private_equity += 1
      elsif @question.case.industry == "Pharmaceuticals"
        @user.pharmaceuticals += 1
      elsif @question.case.industry == "Airline"
        @user.airline += 1
      elsif @question.case.industry == "Technology, Media & Telecommunication"
        @user.tmt += 1
      elsif @question.case.industry == "Non-profit"
        @user.non_profit += 1
      elsif @question.case.industry == "Public sector"
        @user.public_sector += 1
      end

    else
      @answer.correctness = "Very good. Keep up the good work! 😎"
      @user.score += 2
      @attempt.score += 2

      if @question.skills == "Logic and rigorous thinking"
        @user.logic += 2
      elsif @question.skills == "Business sense & culture"
        @user.business_sense += 2
      elsif @question.skills == "Mathematics skills"
        @user.mathematics += 2
      end

            if @question.case.industry == "Consumer goods"
        @user.consumer_goods += 2
      elsif @question.case.industry == "Oil & gas"
        @user.oil_and_gas += 2
      elsif @question.case.industry == "Manufacturing"
        @user.manufacturing += 2
      elsif @question.case.industry == "Financial services"
        @user.financial_services += 2
      elsif @question.case.industry == "Private Equity"
        @user.private_equity += 2
      elsif @question.case.industry == "Pharmaceuticals"
        @user.pharmaceuticals += 2
      elsif @question.case.industry == "Airline"
        @user.airline += 2
      elsif @question.case.industry == "Technology, Media & Telecommunication"
        @user.tmt += 2
      elsif @question.case.industry == "Non-profit"
        @user.non_profit += 2
      elsif @question.case.industry == "Public sector"
        @user.public_sector += 2
      end

    end
    @user.save
    @attempt.save
    @next_question = Question.where(position: @question.position + 1, case_id: @question.case.id).last
    @answers = Answer.where(question_id: @question.id)
    authorize @answer
  end

  def voting
    @answer = Answer.find(params[:id])
    @answer.votes = @answer.votes + 1
    @answer.save
    authorize @answer
    redirect_to answer_path(@answer)
  end

  private

  def answer_params
    params.require(:answer).permit(:id, :content, :votes, :correctness, :question_id, :attempt_id)
  end

end

app/views/answers/index.html.erb
<br><br><br><br><br>
<% @users.each do |a| %>
  <p>Email : <%= a.email %></p>
  <p>Created at : <%= a.created_at %></p>
  <p>Updated at : <%= a.updated_at %></p>
  <p>Score : <%= a.score %></p>
  <p>Suscribed : <%= a.suscribed %></p>
  <p>______</p>

<% end %>

app/views/answers/show.html.erb
<div class="trianglify-twisted">
  <div class="first-box">
    <div class="row">
      <div class="col col-md-12">
        <h2 class="title-question"> <%= @question.case.name.upcase %> <%= @question.case.difficulty.html_safe  %></h2>
      </div>

    </div>
    <div class="row">
      <div class="col col-md-12">

        <div class="progress md-progress" style="height: 20px">
          <div class="progress-bar progress-bar-bis" role="progressbar" style="width: <%= @question.position.to_i.fdiv(@question.case.questions.last.position.to_i) * 100 %>%" aria-valuenow="<%= @question.position.to_i.fdiv(@question.case.questions.last.position.to_i) * 100%>" aria-valuemin="0" aria-valuemax="100">
          </div>

      </div>


      <p class="text-right"> <em> <%= @question.case.questions.last.position.to_i %> questions</em></p>
            <h4 class="disclaimer">For qualitative questions, our correction algorithms is based on keywords, as there are specific notions you are meant to mention for qualitative questions. Thus, your score is indicative and not definitive. For quantitative questions, you should have the exact result to get the points. .</h4>

      </div>
    </div>
    <div>

    <div class="row">
      <div class="col col-md-4 offset-md-4">
        <div class="container-question container-correct">
          <p class="correctness"> <strong> <%= @answer.correctness %> </strong> </p>
        </div>
      </div>
      <div class="col col-md-4 position-of-button">
          <% if @next_question.nil? %>
          <h4 class="label-button">SEE MY SCORE</h4 class="label-button">
          <%= link_to "", case_questions_path(@question.case), class: "btn btn-next" %>
        <% else %>
          <h4 class="label-button">NEXT QUESTION</h4 class="label-button">
          <%= link_to "", question_path(@next_question), class: "btn btn-next" %>
        <% end %>
      </div>
    </div>



    </div>
    <div class="row">
      <div class="col col-md-12">
        <div class="container-question-blue">
          <div class="question-text">
            <h5> <%=  @question.content.gsub(/\n/,'<br>').html_safe %></h5>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col col-md-12">
        <div class="container-question">
            <h6>Your answer</h6>
            <p class="question-answer"> <%= @answer.content.gsub(/\n/,'<br>').html_safe %></p>
        </div>
      </div>
<!--       <div class="col col-md-8">
        <div class="container-question">
          <h6>Correction</h6>
              <p class="question-correction"> <%= @question.correction.gsub(/\n/,'<br>').html_safe %></p>
        </div>
      </div> -->
    </div>

    <div class="row">
      <div class="col col-md-12">
        <div class="container-question">
          <h6>Correction</h6>
              <p class="question-correction"> <%= @question.correction.gsub(/\n/,'<br>').html_safe %></p>
        </div>
      </div>
    </div>


    <!-- <div class="row">
      <div class="col col-md-12">
          <div class="container-question">
              <h6 class="best-answers">  What are other best candidates 5 best answers? 🙌 </h6>

                <% @answers.all.order('votes DESC').first(5).each do |answer| %>
                  <div class="notification">

                <% if @user.photo.url.nil? %>
                  <%=  image_tag "avatar.png", width: 150, height: 150, class: "avatar dropdown-toggle", style: "background: white" %>
                <% else %>
                  <%= cl_image_tag @user.photo, width: 150, height: 150, crop: :thumb, gravity: :face, class: "avatar dropdown-toggle" %>
                <% end %>


              <div class="notification-content">
                <p class="answer-content"> <strong> <%= answer.attempt.user.first_name %>: </strong> <%=  answer.content.gsub(/\n/,'<br>').html_safe %>  </p>
              </div>
              <div class="notification-actions">
                <p><%= link_to '<i class="far fa-thumbs-up"></i>'.html_safe, voting_path(answer) %></p>
                  <p><%= answer.votes %> votes </p>
              </div>
            </div>
          <% end %>
        </div>
    </div>
 -->
</div>















    <div class="row next-quest-last">
      <div class="col col-md-4 offset-md-4">
        <div class="container-question container-correct">
          <p class="correctness"> <strong> <%= @answer.correctness %> </strong> </p>
        </div>
      </div>
      <div class="col col-md-4 position-of-button">
          <% if @next_question.nil? %>
          <h4 class="label-button">SEE MY SCORE</h4 class="label-button">
          <%= link_to "", case_questions_path(@question.case), class: "btn btn-next" %>
        <% else %>
          <h4 class="label-button">NEXT QUESTION</h4 class="label-button">
          <%= link_to "", question_path(@next_question), class: "btn btn-next" %>
        <% end %>
      </div>
    </div>

</div>
</div>
</div>
</div>
</div>
</div>


  <div class="footer">
    <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright">
      Get to the best consulting firms <i class="fas fa-heart"></i>
    </div>
  </div>